#!/bin/sh
mkdir -p build
cd build \
&& cmake \
  -DWITH_ALEMBIC=ON \
  -DWITH_MOD_OCEANSIM=ON \
  -DWITH_CODEC_FFMPEG=ON \
  -DWITH_CODEC_SNDFILE=ON \
  -DWITH_INSTALL_PORTABLE=OFF \
  -DWITH_FFTW3=ON \
  -DWITH_SDL=OFF \
  -DWITH_OPENCOLORIO=ON \
  -DWITH_OPENSUBDIV=ON \
  -DPYTHON_LIBRARY=$PYTHON_LIBRARY \
  -DPYTHON_LIBPATH=$PYTHON_LIBPATH \
  -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR \
  -DPYTHON_VERSION=$PYTHON_VERSION \
  -DWITH_PYTHON_INSTALL=OFF \
  -DWITH_PYTHON_INSTALL_NUMPY=OFF \
  -DPYTHON_NUMPY_PATH=$PYTHON_NUMPY_PATH \
  -DPYTHON_NUMPY_INCLUDE_DIRS=$PYTHON_NUMPY_INCLUDE_DIRS \
  -DWITH_OPENVDB=ON \
  -DWITH_TBB=ON \
  -DWITH_IMAGE_OPENJPEG=ON \
  -DWITH_GHOST_WAYLAND=OFF \
  -DCMAKE_INSTALL_PREFIX=../install \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
  ../blender
